export const TEXTS = {
  auth: {
    loginTitle: 'Iniciar Sesión',
    registerTitle: 'Crear Cuenta',
    recoverTitle: 'Recuperar Contraseña',
    newPasswordTitle: 'Nueva Contraseña',
    emailLabel: 'Correo electrónico',
    passwordLabel: 'Contraseña',
    confirmPasswordLabel: 'Confirmar Contraseña',
    nombreLabel: 'Nombre completo',
    loginBtn: 'Iniciar Sesión',
    registerBtn: 'Registrarse',
    sendEmailBtn: 'Enviar enlace',
    savePasswordBtn: 'Guardar contraseña',
    goToLogin: '¿Ya tienes cuenta? Inicia sesión',
    goToRegister: '¿No tienes cuenta? Regístrate',
    forgotPassword: '¿Olvidaste tu contraseña?',
  },
  errors: {
    sessionExpired: 'Tu sesión ha expirado. Por favor, inicia sesión nuevamente.',
    requiredField: 'Este campo es requerido',
    invalidEmail: 'Ingresa un correo electrónico válido',
    passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
    passwordMismatch: 'Las contraseñas no coinciden',
    loginFailed: 'Credenciales incorrectas',
    genericError: 'Ocurrió un error inesperado',
  },
  platform: {
    title: 'Manchita Skills',
    subtitle: 'Sistema de Gestión',
    userManagement: 'Gestión de Usuarios',
    roleManagement: 'Gestión de Roles',
    profile: 'Mi Perfil',
    logout: 'Cerrar Sesión',
    support: 'Soporte y Ayuda',
  },
  actions: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    create: 'Crear',
    confirm: 'Confirmar',
    close: 'Cerrar',
    yes: 'Sí',
    no: 'No',
  },
  confirmations: {
    deleteTitle: 'Confirmar eliminación',
    deleteMessage: '¿Estás seguro de que deseas eliminar este registro?',
  },
};
